# Generated by Django 4.1.3 on 2022-11-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessoryid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("view", models.PositiveIntegerField()),
                ("view_name", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "accessoryid",},
        ),
        migrations.CreateModel(
            name="Accname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("act", models.TextField()),
                ("view_name", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "accname",},
        ),
        migrations.CreateModel(
            name="Cardprefixnametable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("item", models.TextField()),
                ("card_name", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "cardprefixnametable",},
        ),
        migrations.CreateModel(
            name="Item_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("item", models.PositiveIntegerField()),
                ("name_scan", models.TextField()),
                ("name", models.TextField()),
                ("act_scan", models.TextField()),
                ("act", models.TextField()),
                ("caption_scan", models.TextField(max_length=40000)),
                ("caption", models.CharField(max_length=40000)),
                ("card", models.TextField()),
                ("view", models.TextField()),
                ("item_type", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "item_info",},
        ),
        migrations.CreateModel(
            name="itemInfo_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("info_data", models.FileField(upload_to="")),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "itemInfo_data",},
        ),
        migrations.CreateModel(
            name="Num2cardillustnametable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("item", models.TextField()),
                ("card_act", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "num2cardillustnametable",},
        ),
        migrations.CreateModel(
            name="Spriterobeid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("robe_id", models.TextField()),
                ("view", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "spriterobeid",},
        ),
        migrations.CreateModel(
            name="Spriterobename",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creat_user", models.TextField()),
                ("robe_id", models.TextField()),
                ("robe_act", models.TextField()),
                ("robe_id_eng", models.TextField()),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "spriterobename",},
        ),
        migrations.CreateModel(
            name="User_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("login_time", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T1", "type 1"),
                            ("T2", "type 2"),
                            ("T3", "type 3"),
                            ("T4", "type 4"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "user_data",},
        ),
    ]
